% -------------------------------------------------------------------
%  Generated by MATLAB on 7-Oct-2015 02:12:56
%  MATLAB version: 8.4.0.150421 (R2014b)
% -------------------------------------------------------------------
saveVarsMat = load('Sara_cyclindercircles.mat');

ans = 'ybyr';

ax = saveVarsMat.ax; % <1x1 matlab.graphics.axis.Axes> unsupported class

centers = ...
  [0 0;
   0 0;
   0 0;
   0 0];

color = 'ybyr';

r = 1;

r1 = 2;

clear saveVarsMat;
